[project]
name = "untitled-sekai"
version = "0.1.0"
description = ""
authors = [
    {name = "Piliman22",email = "piliman.sab@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3 (>=1.38.41,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
